version: '3.8'
services:

  lis-notificator:
    image: lis-notificator
    restart: on-failure
    network_mode: "host"
    env_file:
      - ./default.env

    command: java --enable-preview -jar -XX:ParallelGCThreads=8 -XX:+UseZGC target/youtrade.cs-autotrade-telegram-service-1.0.0.jar