version: '3.8'
services:

  youtrade-autotrade-telegram-service:
    image: youtrade.cs-autotrade-telegram-service
    restart: on-failure
    network_mode: "host"
    env_file:
      - ./default.env

    command: >
      java 
      --enable-preview 
      -XX:+UseShenandoahGC
      -Xms512m -Xmx1024m
      -XX:ShenandoahGCHeuristics=adaptive
      -jar target/youtrade-autotrade-telegram-service-1.0.0.jar